name: "Install xmipp4-core"
description: "Build and install xmipp4-core from source"

inputs:
  ref:
    description: "Branch or tag in the xmipp4-core repo"
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@main
      with:
        repository: gigabit-clowns/xmipp4-core
        ref: ${{ inputs.ref }}
        path: xmipp4-core
        token: ${{ secrets.READ_TOKEN_MARTIN }}

    - name: Configure and build with CMake
      uses: threeal/cmake-action@main
      with:
        source-dir: "${{ github.workspace }}/xmipp4-core"
        build-dir: "${{ github.workspace }}/xmipp4-core/build"
        run-build: true

    - name: Install
      shell: bash
      working-directory: "${{ github.workspace }}/xmipp4-core"
      run: cmake --install build

    - name: Cleanup
      shell: bash
      run: rm -rf "${{ github.workspace }}/xmipp4-core"
